version: '3.1'

services:
  app:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "15781:15781"
      - "15788:15788"
      - "15722:22"
